新增地图: ze_ffvii_cosmo_canyon_v6test5
fyscs/servers-config pull request #2537
Opened 2023-08-26 01:36 UTC by ShengJianPhy

## 该PR作用的地图是(仅英文小写)
ze_ffvii_cosmo_canyon_v6test5.
## 为什么要增加/修改这个东西
新增地图entwatch.cfg
修改地图参数:修改了黑洞雷,屏障雷,冰冻雷的购买数量,增加了地图尸变时间(因为这张图出生点开个门就要25秒多了)
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2023-08-26 13:31 UTC, Kxnrl requested changes

2023-08-26 13:31 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/ze_ffvii_cosmo_canyon_v6test5.cfg
> +zr_infect_spawntime_max "45.0"
太久了

2023-08-26 13:42 UTC, ShengJianPhy commented on ZombiEscape/cfg/sourcemod/map-configs/ze_ffvii_cosmo_canyon_v6test5.cfg
> +zr_infect_spawntime_max "45.0"
fiexed

2023-08-27 14:22 UTC, Kxnrl approved these changes

2023-08-27 14:22 UTC, merged