修改地图翻译: ze_ffvii_cosmo_canyon_v6test5
fyscs/servers-config pull request #2557
Opened 2023-09-04 04:36 UTC by ShengJianPhy

## 该PR作用的地图是(仅英文小写)
ze_ffvii_cosmo_canyon_v6test5
## 为什么要增加/修改这个东西
新增倒计时,boss技能提示
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2023-09-04 09:54 UTC, Kxnrl requested changes

2023-09-04 09:54 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_ffvii_cosmo_canyon_v6test5.txt
> +        "chi" "吉纳塔克正在蓄力终极,15秒后所有人类变为一血"
这里翻译文件不会触发

2023-09-04 09:54 UTC, Kxnrl commented
Countdown config is missing!

2023-09-04 10:11 UTC, ShengJianPhy commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_ffvii_cosmo_canyon_v6test5.txt
> +        "chi" "吉纳塔克正在蓄力终极,15秒后所有人类变为一血"
fixed

2023-09-12 16:48 UTC, Kxnrl approved these changes

2023-09-12 16:48 UTC, merged